origincert: /etc/cloudflared/cert.pem

tunnel: bluwale-tunnel

credentials-file: #REDACTED

#will only be able to access domains if connected to vpn and if tunnel is up, otherwise will get 502 error 
# Force the tunnel transport to HTTP/2 (TCP) for better reliability on ISPs that degrade UDP/QUIC

protocol: http2


ingress:

  - hostname: nextcloud.REDACTED

    service: #REDACTED


  - hostname: home.REDACTED

    service: #REDACTED


  - hostname: frigate.REDACTED

    service: #REDACTED


  - hostname: emr.REDACTED

    service: #REDACTED


  - hostname: wedding.REDACTED

    service: #REDACTED


  - hostname: hls.REDACTED

    service: #REDACTED


  # default catch-all

  - service: http_status:404
